### PR TITLE
Don't output exception if trying to attach

### PR DESCRIPTION
**Pull request by sschneid**
except silently and continue attachment attempts if a previously set-up
cluster is no longer reachable.

### CODE REVIEW

**Comment by kensipe** [comment]
This has better error handling... however it doesn't fix the underlying issue... the cluster is not authorized.

```
shakedown --dcos-url http://ken-2ajht-elasticl-bevprg0pzd9j-1830827653.us-west-2.elb.amazonaws.com/ tests/acceptance/
   ____________
  ▐ ▚ ▖    ▗ ▞ ▌
  ▐  ▚ ▘▗▖▝ ▞  ▌ 》mesosphere shakedown v1.4.5
  ▐  ▞▚▝  ▘▞▚  ▌ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ━━  ━
  ▝▞▘  ▚  ▞  ▝▚▘
        ▚▞

> Running pre-flight checks...
  - Checking for dcos library... 0.5.3
  - Checking for pytest library... 3.1.2
  - Authenticating with DC/OS cluster... 
    - trying OAuth token... ✕ 
error: no authentication credentials or token found.
✘-1 ~/projects/shakedown [pr-162 L|✔] 
```

**Comment by sschneid** [comment]
@mesosphere-ci retest this please

**Comment by sschneid** [comment]
@mesosphere-ci retest this please

**Comment by sschneid** [comment]
@mesosphere-ci retest this please

**Comment by sschneid** [comment]
@mesosphere-ci retest this please

**Comment by sschneid** [comment]
@mesosphere-ci retest this please

**Comment by sschneid** [comment]
Test failures are unrelated to this patch, but rather failures to provision in CloudFormation.  When a cluster was able to be provisioned, here are the (passing) build results:

- open: https://jenkins.mesosphere.com/service/jenkins/job/public-shakedown-pulls/190/channel=testing%2Fmaster,label=py35,variant=open/console
- ee: https://jenkins.mesosphere.com/service/jenkins/job/public-shakedown-pulls/195/channel=testing%2Fmaster,label=py35,variant=ee/console

**Pull request merged**
