### PR TITLE
adding lookup for master leader and marathon leader

### PR DESCRIPTION
**Pull request by kensipe**

### CODE REVIEW

**Comment by sschneid** [comment]
@mesosphere-ci retest this please

**Comment by sschneid** [comment]
@mesosphere-ci retest this please

**Comment by sschneid** [comment]
👍, needs docs.

**Comment by kensipe** [comment]
@sschneid this is ready for review and merge.
also.. there are a number of API changes we should make based on this.  any method for "master" is suspect.   In most cases, this should probably be the leader.  Unless any pseudo random master will do :)

**Pull request merged**
