### PR TITLE
Bump dcoscli version to `0.4.14`

### PR DESCRIPTION
**Pull request by sschneid**

### CODE REVIEW

**Comment by sschneid** [comment]
@mesosphere-ci retest this please

**Comment by sschneid** [comment]
@mesosphere-ci retest this please

**Comment by kensipe** [comment]
@sschneid is is falling victim to the same challenge my PR is having.   periodically the json_options fails.   we need to understand why that is.

**Comment by kensipe** [comment]
once we get the test working this lgtm

**Pull request merged**
