### PR TITLE
adding ability to get a package versions from shakedown

### PR DESCRIPTION
**Pull request by kensipe**
Still need to 1) add to API docs and 2) create a test

### CODE REVIEW

**Comment by kensipe** [comment]
@sschneid this is ready to go.   Not sure what is up with the tests.

**Comment by kensipe** [comment]
retest this please

**Comment by kensipe** [comment]
retest this please

**Comment by kensipe** [comment]
retest this please

**Comment by kensipe** [comment]
retest this please

**Comment by kensipe** [comment]
there were issues initially with cluster creation... that is solved now.    It failed last for unknown reasons.   The full task suite passes on my machine.

**Comment by sschneid** [comment]
@mesosphere-ci retest this please

**Pull request merged**
