### PR TITLE
master http service

### PR DESCRIPTION
**Pull request by kensipe**
adding the ability to have an http service to host artifacts to be fetched from mesos tasks

### CODE REVIEW

**Comment by sschneid** [comment]
@mesosphere-ci retest this please

**Comment by sschneid** [comment]
@mesosphere-ci retest this please

**Comment by sschneid** [comment]
We have `kill_process_on_host()` which should work on both master and agents; could `kill_process_from_pid_file_on_master()` be swapped to something more generic, such as `kill_pid_on_host()` and maybe `kill_pid_from_file_on_host()` (or similar)?

In addition, I think having a default of `python_http.pid` for the pidfile is undesirable (at least to me).

**Comment by kensipe** [comment]
@sschneid updates in.

**Pull request merged**
