### PR TITLE
adding trailing slash for service calls

### PR DESCRIPTION
**Pull request by kensipe**

### CODE REVIEW

**Comment by sschneid** [comment]
👍 , will merge when tests pass.

**Comment by mgummelt** [comment]
This broke dcos-commons tests

**Comment by kensipe** [comment]
There is a change coming in DCOS which would not accept the lack of a trailing slash.  that would have affected all clients.   This was the best course of action.

**Comment by sschneid** [comment]
Sorry about that @mgummelt -- this was definitely not intended to be a breaking change!  Can you provide details on why this broke dcos-commons?  I'd like to add a test for this scenario so that something similar doesn't happen again.

**Comment by mgummelt** [comment]
Ken, what DCOS change?

**Pull request merged**
