### PR TITLE
Fix documentation for get_private_agents()

### PR DESCRIPTION
**Pull request by loren**

### CODE REVIEW

**Comment by kensipe** [comment]
@loren this is incorrect.   `get_agents` gets all the agents `get_private_agents` get only private and there is one for public as well.

**Comment by loren** [comment]
OK, thanks. This is what I am seeing on that page and it does look incorrect to me, but no problem if that's how it's supposed to be.
screen shot 2016-10-31 at 3 47 15 pm

**Comment by sschneid** [comment]
Oops!  Good catch, sorry about that @loren!

**Comment by loren** [comment]
Happy to help, @sschneid

**Pull request merged**
